radixconfig.yaml, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Controllers/ShipmentController.cs, src/ChemDec.Api/Model/ChemicalBase.cs, src/ChemDec.Api/Model/ChemicalData.cs, src/ChemDec.Api/Model/ChemicalsByDay.cs, src/ChemDec.Api/Model/ChemicalsByTotal.cs, src/ChemDec.Api/Model/ChemicalsEnums.cs, src/ChemDec.Api/Model/GraphData.cs, src/ChemDec.Api/Model/Nitrogen.cs, src/ChemDec.Api/Model/NitrogenPending.cs, src/ChemDec.Api/Model/Toc.cs, src/ChemDec.Api/Model/TocPending.cs, src/ChemDec.Api/Model/Water.cs, src/ChemDec.Api/Model/WaterPending.cs
Change chemical response
Closes #17,#15
=> fix: change the chemical response

radixconfig.yaml, src/ChemDec.Api/Program.cs
=> fix: cors issues

src/ChemDec.Api/Controllers/Handlers/InstallationHandler.cs, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Controllers/InstallationController.cs, src/ChemDec.Api/Controllers/ShipmentController.cs, src/ChemDec.Api/Model/ChemicalBase.cs, src/ChemDec.Api/Model/ChemicalsEnums.cs, src/ChemDec.Api/Model/GraphData.cs
change the response model
Closes #15
=> fix: change the response model

src/ChemDec.Api/Controllers/Handlers/InstallationHandler.cs, src/ChemDec.Api/Controllers/InstallationController.cs, src/ChemDec.Api/Model/ReservoirData.cs
fix to the reservoir data endpoint and some refactor
Closes #15
=> fix: reservoir data endpoint

src/ChemDec.Api/Controllers/Handlers/InstallationHandler.cs
=> fix: add planned execution condition

src/ChemDec.Api/Datamodel/Shipment.cs
=> fix: remove water analysis id

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Model/Shipment.cs
=> fix: shipment post api changes

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> fix: post api changes and refactor

src/ChemDec.Api/ChemDec.Api.csproj, src/ChemDec.Api/Program.cs
=> fix: date serialization

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Controllers/ShipmentController.cs
=> fix: sending email

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Model/Attachment.cs
add comments and attachments to the post endpoint
=> feat: add comments and attachment

radixconfig.yaml
=> fix: remove the variables

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
initialize attachments object
Closes #62
=> fix: initialize attachments object

src/ChemDec.Api/ChemDec.Api.csproj, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Controllers/ShipmentController.cs, src/ChemDec.Api/Datamodel/Comment.cs, src/ChemDec.Api/Infrastructure/Services/CommentsService.cs, src/ChemDec.Api/Infrastructure/Services/ICommentsService.cs, src/ChemDec.Api/Model/Shipment.cs, src/ChemDec.Api/Program.cs
fixing adding new comment and refactor
=> fix: adding new comment

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
add new chemicals code back to save
=> fix: add new chemicals

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> fix: uncomment updated check

README.md, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> feat: add simple documentation

src/ChemDec.Api/Controllers/AccountController.cs, src/ChemDec.Api/Controllers/AdminController.cs, src/ChemDec.Api/Controllers/ChemicalController.cs, src/ChemDec.Api/Controllers/InstallationController.cs, src/ChemDec.Api/Controllers/ShipmentController.cs, src/ChemDec.Api/Program.cs, src/ChemDec.Api/appsettings.json
=> fix: cors fix

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> fix: shipment approval bug

radixconfig.yaml, src/ChemDec.Api/Controllers/AdminController.cs, src/ChemDec.Api/Controllers/ChemicalController.cs, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Controllers/InstallationController.cs, src/ChemDec.Api/Controllers/ShipmentController.cs, src/ChemDec.Api/Program.cs, src/ChemDec.Api/appsettings.json
=> fix: cors test and fix

src/ChemDec.Api/Controllers/EmailTestController.cs, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> feat: test email

src/ChemDec.Api/ChemDec.Api.csproj, src/ChemDec.Api/Controllers/EmailTestController.cs, src/ChemDec.Api/Program.cs
update keyvault config package
=> chore: update keyvault config package

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/appsettings.json
fix delete chemicals issue and update chemicals email in config
=> fix: delete chemicals

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
fix object reference error when updating chemicals
=> fix: object reference error

src/ChemDec.Api/Controllers/ChemicalController.cs, src/ChemDec.Api/Controllers/Handlers/ChemicalHandler.cs
fix new chemical email sending
=> fix: new chemical email

src/ChemDec.Api/Controllers/ChemicalController.cs
remove commented role assignment
=> fix: remove comment

src/ChemDec.Api/Controllers/ChemicalController.cs
=> fix: role check not required

src/ChemDec.Api/Controllers/EmailTestController.cs, src/ChemDec.Api/Controllers/Handlers/ChemicalHandler.cs, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Infrastructure/Utils/MailSender.cs, src/ChemDec.Api/appsettings.json
=> feat: graph email changes

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> fix: update broken links

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> fix: email content change

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> fix: email template update

src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs
=> fix: plant id in the url

src/ChemDec.Api/Infrastructure/Utils/UserService.cs
admin should have chemical responsible role.
=> feat: admin should have chemical responsible role

.github/workflows/build.yml, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Model/ShipmentChemicalTableItem.cs, src/IntegrationTests/IntegrationTests.csproj
add shipment information and water volumes
=> feat: add shipment information and water volumes

src/Application/Shipments/Queries/GeyShipmentById/GetShipmentByIdQueryHandler.cs, src/Application/Shipments/Queries/GeyShipmentById/GetShipmentByIdQueryResult.cs
=> feat: adding sender id

src/ChemDec.Api/Program.cs
=> feat: uncomment background job code

src/ChemDec.Api/Program.cs, src/Infrastructure/Persistance/Repositories/EmailNotificationsRepository.cs
Email notification implementation.
=> feat: implement email notification

src/Application/Shipments/Commands/Submit/SubmitShipmentCommandHandler.cs
Email body is showing proper in EmailNotificationJob.
Actual : **System.Func`1[System.String]**Shipment form was submitted to Sture Submitted by Jone Torgersen (Bouvet ASA) on Oseberg C ([JONET@equinor.com](mailto:JONET@equinor.com))
Expected : **[DEV]** Shipment form was submitted to Sture Submitted by Jone Torgersen (Bouvet ASA) on Oseberg C ([JONET@equinor.com](mailto:JONET@equinor.com))
=> fix: email notification body issue resolve

.github/workflows/build.yml
Enabling integration testing workflow just for testing.
=> fix: enable intergation test

src/ChemDec.Api/Controllers/AccountController.cs, src/ChemDec.Api/Controllers/Handlers/AdminHandler.cs, src/ChemDec.Api/Controllers/Handlers/ChemicalHandler.cs, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Controllers/HomeController.cs, src/ChemDec.Api/Controllers/ShipmentController.cs, src/ChemDec.Api/Datamodel/ChemContext.cs, src/ChemDec.Api/Infrastructure/Security/ChemAuthenticationHandler.cs, src/ChemDec.Api/Infrastructure/Services/CommentsService.cs, src/ChemDec.Api/Model/Notification.cs
fix: calulated_weight_is_always_zero 
solution - applied calculation in backend
#189
=> fix: calulatedweight_is_always

src/ChemDec.Api/Model/ShipmentChemical.cs
fix: removed fields from backend as they are not needed in payload.
#189
=> fix: calulatedweight is always 0

src/ChemDec.Api/ChemDec.Api.csproj, src/ChemDec.Api/Controllers/Handlers/ChemicalHandler.cs, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Infrastructure/Services/CommentsService.cs, src/ChemDec.Api/Infrastructure/Utils/LoggerHelper.cs, src/ChemDec.Api/Program.cs
feat: added open telemetry
#91
=> feat: added open telemetry

src/ChemDec.Api/ChemDec.Api.csproj, src/ChemDec.Api/Controllers/Handlers/ChemicalHandler.cs
fix: added fix for validating the chemical name when editing an existing chemical
#16 
Also refactored and optimized code handling some edge cases when entering chemical name.
=> fix: validate name when editing chemical

src/ChemDec.Api/Controllers/Handlers/InstallationHandler.cs, src/ChemDec.Api/Controllers/InstallationController.cs
solution : converted all the measure unit like ppm,m3 into kg 
#36
=> feat: make the unit type for the reservoir data endpoint consistent

CONTRIBUTING.md
chore: create contributing.md file
=> chor: create contributing.md file

src/ChemDec.Api/Controllers/Handlers/ChemicalHandler.cs
fix: removed InvariantCultureIgnoreCase as it is not supported in remote linq query. we already have tolower
=> fix: resolved issue while creating chemical

src/ChemDec.Api/Controllers/Handlers/ChemicalHandler.cs, src/ChemDec.Api/Controllers/Handlers/ShipmentHandler.cs, src/ChemDec.Api/Model/ShipmentChemicalTableItem.cs
1) Separated chemical history record if different measurement unit and density is 0
2) Grouped chemical history records if same measurement unit and density is 0
3) Grouped rest of the records based on sender, chemical and measurement unit and summed all the weight and amount.
=> feat: separated chemical history rows
